# Generated by Django 3.1.6 on 2021-02-17 15:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0001_initial'),
    ]     

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario')], default=1),
            preserve_default=False,
        ),
    ]
