# Generated by Django 3.1.6 on 2021-02-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TesisApp', '0003_auto_20210217_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Rol',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Usuario')]),
        ),
    ]
